version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 8093:8093
    environment:
      - PORT=8093
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 8091:8091
    environment:
      - PORT=8091
