version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
  envoy:
    image: envoyproxy/envoy:v1.14.4
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 8082:8082
